name: Go test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4 

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.3'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Check if Build and Tests Passed
      run: |
        if [ $? -ne 0 ]; then
          echo "Build or tests failed!"
          exit 1
        else
          echo "Build and tests passed!"
        fi
